<div class="modal animated fadeIn product-upsertvar-modal" id="product-bothvar-modal" data-keyboard="false" data-backdrop="static" data-onclose="remove">
    <div class="modal-dialog">
        <div class="modal-content">
            <form class="form clearfix" id="prod-bothvar-upsert-form">
                <input type="hidden" class="hidden d-none" name="hash" value="<?php echo fetch_or_get($hs['csrf_token'],'none') ?>">
                <div class="modal-header">
                    <h4 class="modal-title">
                    	{{TR Product color & size variation}}
                    </h4>
                </div>
                <div class="modal-body">
                    <div class="data-management-page">
                        <div class="data-management-area">
                            <div class="form-group form-field-box">
                                <div class="row clearfix">
                                    <div class="col-sm-12">
                                        <label class="form-label">
                                            {{TR Image}}
                                        </label>
                                        <div class="filed-box" data-form-field="col_img">
                                            <div class="variation-color-image">
                                                <div class="image" id="select-pcsv-image">
                                                    <div class="flex-cont">
                                                        <i class="material-icons">add_a_photo</i>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-12">
                                        <p class="info-message info">
                                            <i class="material-icons">info</i>
                                            {{TR Please select a color variation image for your product and select a color name for this product variant}}.
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group form-field-box">
                                <div class="row clearfix">
                                    <div class="col-sm-12" data-form-field="col_hex">
                                        <label class="form-label">
                                            {{TR Color name}}
                                        </label>
                                        <div class="filed-box" id="var-color-types">
                                            <select data-size="7" title="{{TR Please select the color name}}" class="form-control" data-live-search="true">
                                                <?php foreach ($hs['color_types'] as $hex => $name): ?>        
                                                    <?php if (hs_prod_type_exists(array('prod_id' => $hs['prod_id'],'var_type' => 'color_size','col_hex' => $hex),true)): ?>
                                                        <option  disabled="true" value="<?php echo $hex; ?>">
                                                            <?php echo hs_translate($name); ?>  {{TR Already Exists}}
                                                        </option>
                                                    <?php else: ?>
                                                        <option value="<?php echo $hex; ?>">
                                                            <?php echo hs_translate($name); ?>
                                                        </option>
                                                    <?php endif; ?>
                                                <?php endforeach; ?>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group form-field-box">
                                <div class="row clearfix">
                                    <div class="col-sm-12" data-form-field="sizing">
                                        <label class="form-label">
                                            {{TR Sizing}}
                                        </label>
                                        <div class="filed-box">
                                            <div class="sizing">
                                                <div class="sizes-defining" id="sizes-defining-box">
                                                    <?php foreach ($hs['ps_type']['size_units'] as $id => $val): ?>
                                                        <div class="size-unit">
                                                            <input value="<?php echo $val; ?>" type="checkbox" id="cbox-<?php echo $id; ?>" data-on-change="variant_size_unit" class="size-var-control filled-in chk-col-blue"/>
                                                            <label for="cbox-<?php echo $id; ?>" class="col-blue">
                                                                <?php echo $val; ?>
                                                            </label>
                                                        </div>
                                                    <?php endforeach; ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?php if (isset($hs['ps_type']['expandable'])): ?>
                                <div class="form-group form-field-box">
                                    <div class="row clearfix">
                                        <div class="col-sm-12">
                                            <label class="form-label">
                                                {{TR Additional}}
                                            </label>
                                            <div class="filed-box">
                                                <div class="sizing-addon clearfix size-var" id="sizing-addon">
                                                    <div class="input-group no-mb">
                                                        <div class="input-control">
                                                            <input id="add_su" type="text" class="form-control" placeholder="{{TR Add extra size}}">
                                                        </div>
                                                        <div class="button-control">
                                                            <button disabled type="button" class="btn add-size bg-blue waves-effect btn-sm">
                                                                <i class="material-icons">exposure_plus_1</i>
                                                            </button> 
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <p class="info-message info">
                                                <i class="material-icons">info</i>
                                                {{TR Add custom size unit}}. <strong><?php echo($hs['ps_type']['label']); ?></strong>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            <?php endif; ?>
                            <div class="form-group form-field-box">
                                <div class="row clearfix">
                                    <div class="col-sm-12">
                                        <div class="filed-box">
                                            <div class="variations-list">
                                                <div class="fieldset-title-panel">
                                                    <h4 class="fieldset-title">
                                                        {{TR Combination Options}} (<span class="tot-vars">0</span>)   
                                                    </h4>
                                                    <button class="col-main-red collapse-toggle" id="collapse-toggle" data-toggle="collapse">
                                                        <span class="text-label">{{TR Collapse all}}</span> (<span class="tot-vars">0</span>)
                                                    </button>
                                                </div>
                                                <div class="fieldset-body clearfix" id="variations-list-holder">
                                                    <div class="no-vars" id="no-vars">
                                                        <h5>
                                                            {{TR No combination options yet}}
                                                        </h5>
                                                        <p class="text-center">
                                                            {{TR A list of combination options will be displayed here, in order to add a combination, select the color of the variant and all available sizes to the selected color of the variant}}
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group form-field-box no-mb">
                                <div class="row clearfix">
                                    <div class="col-sm-12 no-mb">
                                        <div class="filed-box">
                                            <div class="btns">
                                                <button data-section-node="main_cancel_btn" type="button" class="btn bg-grey btn-lg btn-custom" data-dismiss="modal" title="{{TR Cancel}}">
                                                    <i class="material-icons">close</i> <span>{{TR Cancel}}</span>
                                                </button>
                                                <button data-section-node="main_submit_btn" type="submit" class="btn bg-light-blue btn-lg btn-custom m-l-15" title="{{TR Add variant}}">
                                                    <i class="material-icons">add</i> <span>{{TR Add variant}}</span>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            <form id="upload-product-csvimg" class="hidden">
                <input type="hidden" class="hidden d-none" name="hash" value="<?php echo fetch_or_get($hs['csrf_token'],'none') ?>">
                <input name="image" type="file" class="hidden" accept="image/*" onchange="$(this).parent('form').submit();">
            </form>
        </div>
    </div>
    <?php echo hs_loadpage('upsert_product/static/js/add_bothvar_script'); ?>
</div>


