<script>
	jQuery(document).ready(function($) {
		"use strict";
		var AUTH_PAGE_CONTAINER   = $("div#auth-page-main-container");
		var AUTH_PAGE_PASSWD_FORM = AUTH_PAGE_CONTAINER.find("form#reset-password-form");
		var AUTH_PAGE_ITEMS_FLW   = AUTH_PAGE_CONTAINER.find("div#prods-items-container");
		var GRID_BLOCK_WIDTH      = (AUTH_PAGE_ITEMS_FLW.width() / 5);

		if (AUTH_PAGE_ITEMS_FLW.width() >= 768 && AUTH_PAGE_ITEMS_FLW.width() <= 1024) {
			GRID_BLOCK_WIDTH = (AUTH_PAGE_ITEMS_FLW.width() / 4);
		}

		else if(AUTH_PAGE_ITEMS_FLW.width() >= 481 && AUTH_PAGE_ITEMS_FLW.width() <= 820) {
			GRID_BLOCK_WIDTH = (AUTH_PAGE_ITEMS_FLW.width() / 3);
		}

		else if(AUTH_PAGE_ITEMS_FLW.width() >= 320 && AUTH_PAGE_ITEMS_FLW.width() <= 480) {
			GRID_BLOCK_WIDTH = (AUTH_PAGE_ITEMS_FLW.width() / 2);
		}

		else if(AUTH_PAGE_ITEMS_FLW.width() <= 320) {
			GRID_BLOCK_WIDTH = AUTH_PAGE_ITEMS_FLW.width();
		}

		var AUTH_PAGE_GRID_CTRL   = {
			infinity_scroll:function (object = null) {
				if (hs_empty(object)) {
					return false;
				}
				else {
					var scrolled  = 20;
					var inter     = setInterval(function(){
						if (object.scrollTop() + object.innerHeight() >= object.get(0).scrollHeight) {
							if (AUTH_PAGE_GRID_CTRL.getoffset()) {
								$.ajax({
									url: '{{CONFIG url}}/req/auth/get_prods',
									type: 'GET',
									dataType: 'json',
									data: {offset: AUTH_PAGE_GRID_CTRL.getoffset()},
								}).done(function(data) {
									if (data.status == 200) {
										AUTH_PAGE_ITEMS_FLW.gridalicious('append',$(data.html));
										scrolled += 20;
						    			object.animate({ scrollTop: scrolled }, (1000));
									}

									else {
										clearInterval(inter);
									}
								}).fail(function(){
									clearInterval(inter);
								});
							}
							else {
								clearInterval(inter);
							}
						}
						else{
							scrolled += 20;
						    object.animate({ scrollTop: scrolled }, (1000));	
						    if (scrolled > (1000 * 1000)) { scrolled = 20;}
						}
					    
					},1100);
				}
			},
			getoffset: function() {
				var items_list = [];
				AUTH_PAGE_ITEMS_FLW.find('div.prod-item').each(function(index, el) {
					items_list.push(Number($(el).attr('data-product-li')));
				});

				var last_item = Math.min.apply(Math, items_list);

				if (last_item && $.isNumeric(last_item)) {
					return last_item;
				}
				else {
					return 0;
				}
			},
			ga_conf: {
				selector: 'div.prod-item',
				gutter: 0,
				width: (GRID_BLOCK_WIDTH),
				animate: true,
				animationOptions: { 
					speed: 100, 
					duration: 200
				}
			}
		}; AUTH_PAGE_ITEMS_FLW.gridalicious(AUTH_PAGE_GRID_CTRL.ga_conf);

		AUTH_PAGE_PASSWD_FORM.ajaxForm({
			url: '{{CONFIG url}}/req/auth/reset_password',
			type: 'POST',
			dataType: 'json',
			beforeSend:function(){
				AUTH_PAGE_PASSWD_FORM.find('button[type="submit"]').attr('disabled', 'true');
				AUTH_PAGE_PASSWD_FORM.find('div[data-form-field]').each(function(index, el) {
					$(this).find('input').removeClass('animated');
					$(this).find('input').removeClass('flash');
					$(this).find('input').removeClass('v-error');
					$(this).find('small.error-message').remove();
				});
			},
			success:function(data) {
				if (data.status == 200) {
					AUTH_PAGE_PASSWD_FORM.find('button[type="submit"]').addClass('success');
					AUTH_PAGE_PASSWD_FORM.find('button[type="submit"]').text("{{TR E-mail sent!}}");

					delay(function() {
						AUTH_PAGE_CONTAINER.find('div#user-auth-modal').fadeOut(300, function() {
							$(this).replaceWith($(data.html));
						});
					},1500);
				} 
				else if(data.status == 400) {
					AUTH_PAGE_PASSWD_FORM.find('button[type="submit"]').removeAttr('disabled');
					AUTH_PAGE_PASSWD_FORM.find('[data-form-field="email"]').append($("<small>",{
						class: 'animated flash error-message',
						text: data.message
					}));
				}
				else if(data.status == 500){
					AUTH_PAGE_PASSWD_FORM.find('button[type="submit"]').text("{{TR Opps..}}");
					delay(function() {
						AUTH_PAGE_CONTAINER.find('div#user-auth-modal').fadeOut(300, function() {
							$(this).replaceWith($(data.html));
						});
					},1500);
				}
			}
		});

		AUTH_PAGE_GRID_CTRL.infinity_scroll(AUTH_PAGE_ITEMS_FLW);
	});
</script>