<script>
	jQuery(document).ready(function($) {
        "use strict";
        
        var PRODS_MNG_PAGE = $("div#products-management-page");
		var USER_PROD_LIST = PRODS_MNG_PAGE.find("table#prods-list");

        PRODS_MNG_PAGE.find('a.pagination-ctrls').on('click',function(event) {
            event.preventDefault();
            event.stopPropagation();
            if ($(this).hasClass('disabled') != true) { 
                var pager_ctrls = PRODS_MNG_PAGE.find('a.pagination-ctrls');
                var this_ctrl   = $(this);
                var prods_list  = PRODS_MNG_PAGE.find('table#prods-list');
                var pager_dir   = (($(this).hasClass('prev')) ? 'up' : 'down');
                var last_row    = prods_list.find('tr[data-prod-list-item]').last().data('prod-list-item');
                var first_row   = prods_list.find('tr[data-prod-list-item]').first().data('prod-list-item');
                var preloader   = PRODS_MNG_PAGE.find('div#table-preloader').removeClass('hidden');
                var pager_ctrls = pager_ctrls.removeClass('disabled');

                $.ajax({
                    url: '{{CONFIG url}}/req/profile/get_draft_products',
                    type: 'GET',
                    dataType: 'json',
                    data: {
                        dir: pager_dir, 
                        last: last_row, 
                        first: first_row,
                    },
                }).done(function(data) {
                    if (data.status == 200) {
                        prods_list.find('tbody').html(data.html);
                    }
                    else{
                        this_ctrl.addClass('disabled');
                    }
                }).fail(function() {
                    $.notify({
                        message: 'Error: Failed to connect to the server. Please check your internet connection',
                    },{
                        allow_dismiss: false,icon_type: "class",type: 'default',timer: 500,
                        placement: {from: "bottom",align: "left"},
                        offset: {x: 40,y: 30},
                        animate: {enter: 'animated fadeInUp',exit: 'animated fadeOutDown'}
                    });
                }).always(function() {
                    delay(function(){
                        preloader.addClass('hidden');
                    },500);
                });
            }
            else {
                return false;
            }
        });
	});
</script>