<div class="modal animated vh-center fadeIn deliv-addr-map-modal" id="delivery-address-map-modal">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="preview-address-wrapper">
                <div class="left-part">
                    <div class="preview-address">
                        <iframe id="mapreview-area" width="100%" height="100%" frameborder="0" src="https://www.google.com/maps/embed/v1/place?key={{CONFIG google_maps_api}}
                            &q=<?php echo($hs['deliv_addr']); ?>" allowfullscreen>
                        </iframe>
                        <div class="loading-bar">
                            <?php echo hs_svg('loading'); ?>
                        </div>
                    </div>
                </div>
                <div class="right-part">
                    <div class="delivery-addr-info">
                        <ul>  
                            <li class="avatar">
                                <img src="{{ME avatar}}" alt="Photo">
                            </li>  
                            <li>
                                <b>
                                    <?php echo($me['address']['full_name']); ?>
                                </b>
                            </li>                
                            <li>
                                <?php echo($me['address']['country']); ?>, <?php echo($me['address']['state']); ?>
                            </li>
                            <li>
                                <?php echo($me['address']['city']); ?>, <?php echo($me['address']['zip_postal']); ?>
                            </li>
                            <li>
                                <?php echo($me['address']['street']); ?>, <?php echo($me['address']['off_apt']); ?>
                            </li>   
                            <li>
                                <span class="modal-controls ok" data-dismiss="modal">
                                    {{TR Okey!}}
                                </span>
                                <span class="modal-controls change-address" id="change-address">
                                    {{TR Change address}}
                                </span>
                            </li>
                        </ul>
                    </div>
                </div> 
            </div>
        </div>
    </div>
</div>