<div class="modal animated fadeIn vh-center" id="change-lang-sortorder-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form class="form" id="form">
                <input type="hidden" class="hidden d-none" name="hash" value="<?php echo fetch_or_get($hs['csrf_token'],'none') ?>">
                <input type="hidden" class="hidden d-none" name="lang_id" value="0">
                <div class="modal-header">
                    <h4 class="modal-title">
                    	{{TR Change language sort order}}
                    </h4>
                </div>
                <div class="modal-body">
                    <div class="data-management-page">
                    	<div class="form-group form-field-box no-mb">
                            <label class="form-label">
                                {{TR Sort item number}}:
                            </label>
                            <div class="filed-box" data-form-field="sort_order">
                                <input name="sort_order" type="number" class="form-control" placeholder="{{TR Enter the sort item number}}">
                            </div>
                            <p class="info-message info">
                                <i class="material-icons">info</i>
                                {{TR Please note that items are sorted in ascending order. That is, the item with number 1 will be first, 2 second, etc.}}
                            </p>
                    	</div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn bg-grey waves-effect tt-up" data-dismiss="modal">{{TR Cancel}}</button>
                    <button type="submit" class="btn bg-light-blue waves-effect tt-up">{{TR Save changes}}</button>
                </div>
            </form>
        </div>
    </div>
</div>