<div class="clearfix" id="backups-management-page">
    <div class="block-header">
        <nav class="breadcrumbs-cust" aria-label="breadcrumb breadcrumb-cust">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{LINK merchant_panel}}">{{TR Control panel}}</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{{LINK merchant_panel/backup}}">
                        {{TR Backups}}
                    </a>
                </li>
                <li class="breadcrumb-item active">
                    {{TR Site backups management}}
                </li>
            </ol>
        </nav>
    </div>
    <div class="alert alert-warning">
        <i class="material-icons">warning</i>
        <strong>{{TR Please note}}:</strong> 
        {{TR to start the process of creating a backup copy of your site, the module of PHP (ZipArchive) must be installed on the server, and also make sure that the root directory of your site is writable by the user of the HTTP web server (www-data), otherwise, the process will fail!}}
    </div>
    <div class="alert alert-info">
        <i class="material-icons">info</i>
        <strong>{{TR Please note}}:</strong>
        {{TR creating a backup may take some time depending on the amount of content on your site, therefore, after clicking the (Create backup) button, wait for the process to complete without leaving the page!}}
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card ajax-ctrl-table">
                <div class="header un-filterable">
                    <h2>{{TR List of all backups}}</h2>
                    <span>
                        {{TR Last backup}}: {{CONFIG last_backup}}
                    </span>
                </div>
                <div class="body table-responsive">
                    <table class="table table-hover no-mb" id="backups-list">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>{{TR Files Backup}} ZIP</th>
                                <th>{{TR SQL Backup}} ZIP</th>
                                <th>{{TR Files Size}}</th>
                                <th>{{TR SQL Size}}</th>  
                                <th>{{TR Created date}}</th>  
                                <th>{{TR Action}}</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (not_empty($hs['backups'])): ?>
                                <?php foreach ($hs['backups'] as $hs['backup_data']): ?>
                                    <?php echo hs_loadpage('backup/includes/backup_li'); ?>
                                <?php endforeach; ?>
                            <?php else: ?>
                                <?php echo hs_loadpage('backup/includes/empty_table'); ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <button title="{{TR Back up}}" type="button" class="fixed-right-bottom btn bg-main-red btn-circle waves-effect waves-circle waves-float" data-toggle="modal" data-target="#confirm-backup-creation-modal">
        <i class="material-icons">add</i>
    </button>
</div>
<?php echo hs_loadpage('backup/modals/confirmations/confirm_backup_creation'); ?>
<?php echo hs_loadpage('backup/modals/confirmations/confirm_backup_removal'); ?>
<?php echo hs_loadpage('backup/modals/long_process_preloader'); ?>
<?php echo hs_loadpage('backup/static/js/backups_management_script'); ?>
