<div class="prod-item" data-product-li="<?php echo $hs['ls_item']['id']; ?>">
	<a href="<?php echo $hs['ls_item']['prod_url']; ?>">
		<div class="prod-img">
			<img src="<?php echo $hs['ls_item']['poster']; ?>" alt="Product picture">

			<?php if ($hs['ls_item']['discount']): ?>
				<span class="discount">
					-<?php echo($hs['ls_item']['discount']); ?>%
				</span>
			<?php endif; ?>
			<span class="total-sales">
				<span class="inline-label">{{TR Sales}}:</span>
				<span class="num">
					<?php echo $hs['ls_item']['sales']; ?>
				</span>
			</span>
		</div>
		<div class="prod-desc">
			<div class="body">	
				<div class="prod-name">
					<h6>
						<?php echo $hs['ls_item']['prod_name']; ?>
					</h6>
				</div>
				<div class="prices">
					<span class="price">
						<?php echo $hs['ls_item']['sale_price']; ?>
					</span>
					<span class="old-price">
						<?php echo $hs['ls_item']['reg_price']; ?>
					</span>
					<?php if (floatval($hs['ls_item']['rating'])): ?>
						<span class="star-icon ml-auto">
							<?php echo hs_svg('star'); ?>
						</span>
						<span class="rating-num">
							<?php echo $hs['ls_item']['rating']; ?>
						</span>
					<?php endif; ?>
				</div>
			</div>
		</div>
		<div class="remove-from-list">
			<button class="delete-wl-item" data-onclick="delete_wl_item">
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M51.9 76.6l25 25c-18.1 20.3-29 47.3-29 77.6 0 79.5 70.7 143.3 177.8 241.7L256 448l30.2-27.2c20.6-18.9 39.9-36.6 57.5-53.3l92.2 92 24-24-383.8-383-24.2 24.1zM464 179.1C464 114.2 414.1 64 349.6 64c-36.4 0-70.7 16.7-93.6 43.9C233.1 80.7 198.8 64 162.4 64c-8.4 0-16.5.9-24.3 2.5l253.7 253.1C437.3 270.9 464 228 464 179.1z"/></svg>
			</button>
		</div>
	</a>
</div>