<!--
Attention, this markup template is not part of the interface as such, 
but is used by this system to send an emails to the users, 
and that is why this file contains linine CSS styles
-->
<div style="background: #fff; border-radius: 5px; border:1px solid #eee; padding: 30px 50px;">
	<h3 style="padding: 0px; margin: 0 0 15px 0; font-size: 24px; line-height: 24px; color: #192a32;">
		{{TR Hello}}: <b>{{name}}</b>,
	</h3>
	<p style="padding: 0; margin: 0 0 30px 0; font-size: 16px; color: #666;">
		{{TR Thank you for you signing up! Click on the link to activate your account}}:
	</p>
	<div style="width: 100%; margin-bottom: 30px;">
		<a href="{{LINK home?activation_token={{em_code}}}}" style="color: #fff; text-decoration: none; background: #ff7676; padding: 15px 30px; border-radius: 5px; border: 1px solid #ff7676; font-size: 13px; line-height: 13px;">{{TR Activate my account}}</a>
	</div>
	<p style="font-size: 12px; color: #999;">
		<span>
			{{CONFIG name}} - {{TR Team}}.
		</span>
	</p>
</div>

