<div class="modal animated vh-center fadeIn confirm-request-decline confirm-action-modal" id="confirm-request-decline-modal" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form id="request-decline-form">
                <input type="hidden" class="hidden d-none" name="hash" value="<?php echo fetch_or_get($hs['csrf_token'],'none') ?>">
                <div class="modal-header">
                    <h4 class="modal-title">{{TR Please confirm your actions!}}</h4>
                </div>
                <div class="modal-body">
                    {{TR Are you sure you want to reject this request? Please note that this action cannot be undone!}}
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn bg-main-red waves-effect">{{TR Yes, Decline it!}}</button>
                    <button type="button" class="btn bg-grey waves-effect" data-dismiss="modal">{{TR No, Cancel}}</button>
                </div>
                <input type="hidden" name="req_id" value="">
            </form>
        </div>
    </div>
</div>