<div class="clearfix" id="account-reviews-page">
    <div class="block-header">
        <nav class="breadcrumbs-cust" aria-label="breadcrumb breadcrumb-cust">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{LINK merchant_panel}}">{{TR Control panel}}</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{{ME url}}">
                        {{ME name}}
                    </a>
                </li>
                <li class="breadcrumb-item active">
                    {{TR Customer reviews}}
                </li>
            </ol>
        </nav>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card ajax-ctrl-table">
                <div class="header un-filterable">
                    <h2>{{TR List of all customer reviews}} (<?php echo($hs['reviews_total']); ?>)</h2>
                </div>
                <div class="body table-responsive">
                    <table class="table common-table no-mb" id="reviews-list">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>{{TR Customer}}</th>
                                <th>{{TR Purchased item}}</th> 
                                <th>{{TR Valuation}}</th>
                                <th>{{TR Rating}}</th>
                                <th>{{TR Review Date}}</th>
                                <th>{{TR Action}}</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (not_empty($hs['reviews'])): ?>
                                <?php foreach ($hs['reviews'] as $hs['rev_data']): ?>
                                    <?php echo hs_loadpage('account_reviews/includes/review_li'); ?>
                                <?php endforeach; ?>
                            <?php else: ?>
                                <?php echo hs_loadpage('account_reviews/includes/empty_table'); ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                    <?php if (not_empty($hs['reviews'])): ?>
                        <div class="data-preloader-wrapper hidden" id="table-preloader">
                            <?php echo hs_loadpage('components/data_preloader'); ?>
                        </div>     
                        <a href="javascript:void(0);" class="pagination-ctrls prev">
                            <i class="material-icons">chevron_left</i>
                        </a>
                        <a href="javascript:void(0);" class="pagination-ctrls next">
                            <i class="material-icons">chevron_right</i>
                        </a>
                    <?php endif; ?> 
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo hs_loadpage('account_reviews/static/js/account_reviews_script'); ?>
