<div class="clearfix" id="reports-management-page">
    <div class="block-header">
        <nav class="breadcrumbs-cust" aria-label="breadcrumb breadcrumb-cust">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{LINK merchant_panel}}">{{TR Control panel}}</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{{LINK merchant_panel/reports}}">
                        {{TR Reports}}
                    </a>
                </li>
                <li class="breadcrumb-item active">
                    {{TR Manage customer's reports}}
                </li>
            </ol>
        </nav>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card ajax-ctrl-table">
                <div class="header">
                    <h2>{{TR List of all reports from users}}</h2>
                    <div class="rows-filter">
                        <input type="text" placeholder="{{TR Search reporter by name}}" id="search-reports">
                        <i class="material-icons search">search</i>
                        <i class="material-icons clear hidden" id="clear-searching-terms">clear</i>
                    </div>
                </div>
                <div class="body table-responsive">
                    <table class="table table-hover no-mb" id="reports-list">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>{{TR Reporter}}</th>
                                <th>{{TR Product}}</th>  
                                <th>{{TR Status}}</th>
                                <th>{{TR Date}}</th>
                                <th>{{TR Action}}</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (not_empty($hs['reports'])): ?>
                                <?php foreach ($hs['reports'] as $hs['report_data']): ?>
                                    <?php echo hs_loadpage('reports/includes/report_li'); ?>
                                <?php endforeach; ?>
                            <?php else: ?>
                                <?php echo hs_loadpage('reports/includes/empty_table'); ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                    <?php if (not_empty($hs['reports'])): ?>
                        <div class="data-preloader-wrapper hidden" id="table-preloader">
                            <?php echo hs_loadpage('components/data_preloader'); ?>
                        </div>
                        <a href="javascript:void(0);" class="pagination-ctrls prev">
                            <i class="material-icons">chevron_left</i>
                        </a>
                        <a href="javascript:void(0);" class="pagination-ctrls next">
                            <i class="material-icons">chevron_right</i>
                        </a>
                    <?php endif; ?> 
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo hs_loadpage('reports/modals/confirmations/confirm_report_removal'); ?>
<?php echo hs_loadpage('reports/static/js/reports_management_script'); ?>
