<div class="modal animated vh-center fadeIn confirm-action-modal" id="confirm-merchant-removal-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form id="form">
                <input type="hidden" class="hidden d-none" name="hash" value="<?php echo fetch_or_get($hs['csrf_token'],'none') ?>">
                <div class="modal-header">
                    <h4 class="modal-title">{{TR Please confirm your actions!}}</h4>
                </div>
                <div class="modal-body">
                    {{TR Are you sure that you want to delete this account? Note that this action is undonable!}}
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn bg-main-red waves-effect">Yes, Delete it!</button>
                    <button type="button" class="btn bg-grey waves-effect" data-dismiss="modal">No, Cancel</button>
                </div>
                <input type="hidden" name="user_id" value="0">
            </form>
        </div>
    </div>
</div>