<div class="clearfix" id="deleted-products-management-page">
    <div class="block-header">
        <nav class="breadcrumbs-cust" aria-label="breadcrumb breadcrumb-cust">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{LINK merchant_panel}}">{{TR Control panel}}</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{{LINK merchant_panel/product_removals}}">
                        {{TR Product deleting}}
                    </a>
                </li>
                <li class="breadcrumb-item active">
                    {{TR Manage deleted products}}
                </li>
            </ol>
        </nav>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card ajax-ctrl-table">
                <div class="header un-filterable">
                    <h2>{{TR List of all deleted market products}}</h2>
                </div>
                <div class="body table-responsive">
                    <table class="table table-hover" id="prods-list">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>{{TR Seller}}</th>
                                <th>{{TR Product name}}</th>
                                <th>{{TR Price}}</th>
                                <th>{{TR Status}}</th>
                                <th>{{TR Orders}}</th>
                                <th>{{TR Sold}}</th>     
                                <th>{{TR Action}}</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (not_empty($hs['requests'])): ?>
                                <?php foreach ($hs['requests'] as $hs['prod_item']): ?>
                                    <?php echo hs_loadpage('product_removals/includes/prod_list_item'); ?>
                                <?php endforeach; ?>
                            <?php else: ?>
                                <?php echo hs_loadpage('product_removals/includes/empty_table'); ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                    <?php if (not_empty($hs['requests'])): ?>
                        <div class="data-preloader-wrapper hidden" id="table-preloader">
                            <?php echo hs_loadpage('components/data_preloader'); ?>
                        </div>
                        <a href="javascript:void(0);" class="pagination-ctrls prev">
                            <i class="material-icons">chevron_left</i>
                        </a>
                        <a href="javascript:void(0);" class="pagination-ctrls next">
                            <i class="material-icons">chevron_right</i>
                        </a>
                    <?php endif; ?> 
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo hs_loadpage('product_removals/modals/confirmations/confirm_removal'); ?>
<?php echo hs_loadpage('product_removals/static/js/product_removals_script'); ?>
