<div class="modal animated vh-center fadeIn create-site-backup-modal confirm-action-modal" id="confirm-backup-creation-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form id="form">
                <input type="hidden" class="hidden d-none" name="hash" value="<?php echo fetch_or_get($hs['csrf_token'],'none') ?>">
                <div class="modal-header">
                    <h4 class="modal-title">{{TR Please confirm your actions!}}</h4>
                </div>
                <div class="modal-body">
                    {{TR Are you sure you want to make a new backup? Please note that this may take several minutes.}}
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn bg-main-red waves-effect">{{TR Yes, Create it!}}</button>
                    <button type="button" class="btn bg-grey waves-effect" data-dismiss="modal">{{TR No, Cancel}}</button>
                </div>
            </form>
        </div>
    </div>
</div>