<?php 
# @*************************************************************************@
# @ @author Mansur Altamirov (Mansur_TL)                                    @
# @ @author_url 1: https://www.instagram.com/mansur_tl                      @
# @ @author_url 2: http://codecanyon.net/user/mansur_tl                     @
# @ @author_email: highexpresstore@gmail.com                                @
# @*************************************************************************@
# @ HighExpress - The Ultimate Modern Marketplace Platform                  @
# @ Copyright (c) 05.07.19 HighExpress. All rights reserved.                @
# @*************************************************************************@

$context = array();
$config = array('theme' => 'v1');
$theme = $config['theme'];
$hs = $context;
$me = array();
$langs = array();
$hs['currencies'] = array();

$hs['ord_stats'] = $ord_stats = array(
    'pending' => 'Pending',
    'processing' => 'Processing',
    'processed' => 'Processed',
    'sent' => 'Sent',
    'shipped' => 'Shipped',
    'canceled' => 'Canceled',
    'expired' => 'Expired',
    'returned' => 'Returned',
    'failed' => 'Failed', 
);

$hs['sizing_types'] = $sizing_types = array(
    "mens_apparel" => array(
        'name' => "Men's Apparel",
        'size_units' => array(
            'XS',
            'S',
            'M',
            'L',
            'XL',
            'XXL',
            'XXXL',
            'XXXXL',
            'XXXXXL',
        )
    ),
    "womens_apparel" => array(
        'name' => "Women's Apparel",
        'size_units' => array(
            'XXS',
            'XS',
            'S',
            'M',
            'L',
            'XL',
            'XXL',
        )
    ),
    "baby_children_apparel" => array(
        'name' => "Baby and Children Apparel",
        'size_units' => array(
            'Newborn',
            '2t',
            '3t',
            '4t',
            '5t',
            '6t',
            '7t',
            '8t',
            '6 Months',
            '12 Months',
            '18 Months',
            '1-2 Years',
            '2-3 Years',
            '3-4 Years',
            '4-5 Years',
            '5-6 Years',
            '6-7 Years',
            '7-8 Years',
            '8-9 Years',
            '9-10 Years',
            '10-11 Years',
            '11-12 Years',
            '12-13 Years',
            '13-14 Years',
            '14-15 Years',
        )
    ),
    "baby_children_shoes" => array(
        'name' => "Baby and Children Shoes",
        'size_units' => range(15, 35)
    ),
    "other_apparel_sizes" => array(
        'name' => "Other apparel sizes",
        'size_units' => array(
            'One size',
            'XS/S',
            'M/L',
            'L/XL',
            '6XL',
            '7XL',
            '8XL',
            'Youth L(14-16)',
            'Youth XL(18-20)',
            'Youth M(10-12)',
            'Youth S(6-8)',
            'Adult',
            'Kid',
        )
    ),
    "numeric_dimensions" => array(
        'name' => "Numeric dimensions",
        'regex' => "/^(?:[0-9]{1,3}\.[0-9]{1,3}|[0-9]{1,3}){1}$/i",
        'expandable' => true,
        'label' => "For Example: 60,100,1000",
        'size_units' => array('0.5','0.7','1','1.5','2.2')
    ),
    "mens_shoes" => array(
        'name' => "Men's Shoes",
        'size_units' => range(39, 49)
    ),
    "womens_shoes" => array(
        'name' => "Women's Shoes",
        'size_units' => range(35, 44)
    ),
    "memory_capacity" => array(
        'name' => "Memory capacity",
        'expandable' => true,
        'label' => "For Example: 512MG, 128MG, 6TB etc...",
        'regex' => "/^[0-9]{1,3}(?:MG|GB|TB){1}$/i",
        'size_units' => array(
            '1GB',
            '2GB',
            '4GB',
            '8GB',
            '16GB',
            '32GB',
            '64GB',
            '128GB',
            '256GB',
            '512GB',
            '1TB',
        )
    ),
    "area_dimensions" => array(
        'name' => "Area dimensions",
        'expandable' => true,
        'label' => "For Example: 2m x 2m, 5.5cm x 12.5cm etc..",
        'regex' => "/^(?:[0-9]{1,3}\.[0-9]{1,3}|[0-9]{1,3})(?:mm|cm|m|kl|in)[\s]{0,3}[x*]{1}[\s]{0,3}(?:[0-9]{1,3}\.[0-9]{1,3}|[0-9]{1,3})(?:mm|cm|m|kl)$/i",
        'size_units' => array(
            '1.4m x 1.4m',
            '3m x 2m',
            '5m x 10m',
            '8in x 24in',
        )
    ),
    "length_dimensions" => array(
        'name' => "Length dimensions",
        'expandable' => true,
        'label' => "For Example: 25cm, 1m, 80cm, 5mm, etc..",
        'regex' => "/^(?:[0-9]{1,3}\.[0-9]{1,3}|[0-9]{1,3})(?:mm|cm|m|kl|in)$/i",
        'size_units' => array(
            '6.5cm',
            '11.5cm',
            '0.5mm',
            '85in',
        )
    ),
    "voltage_units" => array(
        'name' => "Voltage units",
        'expandable' => true,
        'label' => "For Example:  12V, 18V, 24V, etc..",
        'regex' => "/^[0-9]{1,6}[vV]$/i",
        'size_units' => array(
            '3V',
            '5V',
            '9V',
            '220V'
        )
    ),
    "wattage_units" => array(
        'name' => "Wattage units",
        'expandable' => true,
        'regex' => "/^[0-9]{1,6}[wW]$/i",
        'label' => "For Example:  300W, 150W, 500W etc..",
        'size_units' => array(
            '70W',
            '180W',
            '600w',
            '200W',
            '1200W',
            '3500'
        )
    ),
    "weight_units" => array(
        'name' => "Weight units",
        'expandable' => true,
        'regex' => "/^(?:[0-9]{1,3}\.[0-9]{1,3}|[0-9]{1,3})(?:mg|g|kg|lb|oz)$/i",
        'label' => "For Example:  10kg, 3kg, 5kg, etc..",
        'size_units' => array(
            '100mg',
            '10lb',
            '5.5g',
        )
    ),
    "litre_capacity" => array(
        'name' => "Litre capacity",
        'expandable' => true,
        'regex' => "/^(?:[0-9]{1,3}\.[0-9]{1,3}|[0-9]{1,3})(?:mL|L)$/i",
        'label' => "For Example:  80mL, 100mL, 250mL, etc..",
        'size_units' => array(
            '5mL',
            '10mL',
            '20mL',
            '60mL',
        )
    ),
);

$hs['color_types'] = $color_types = array(
    "800000" => "Maroon",
    "8B0000" => "Dark Red",
    "B22222" => "Fire Brick",
    "FF0000" => "Red",
    "FA8072" => "Salmon",
    "FF6347" => "Tomato",
    "FF7F50" => "Coral",
    "FF4500" => "Orange Red",
    "D2691E" => "Chocolate",
    "F4A460" => "Sandy Brown",
    "FF8C00" => "Dark Orange",
    "FFA500" => "Orange",
    "B8860B" => "Dark Goldenrod",
    "DAA520" => "Goldenrod",
    "FFD700" => "Gold",
    "808000" => "Olive",
    "FFFF00" => "Yellow",
    "9ACD32" => "Yellow Green",
    "ADFF2F" => "Green Yellow",
    "7FFF00" => "Chartreuse",
    "7CFC00" => "Lawn Green",
    "008000" => "Green",
    "00FF00" => "Lime",
    "32CD32" => "Lime Green",
    "00FF7F" => "Spring Green",
    "00FA9A" => "Medium Spring Green",
    "40E0D0" => "Turquoise",
    "20B2AA" => "Light Sea Green",
    "48D1CC" => "Medium Turquoise",
    "008080" => "Teal",
    "008B8B" => "Dark Cyan",
    "00FFFF" => "Aqua",
    "00FFFF" => "Cyan",
    "00CED1" => "Dark Turquoise",
    "00BFFF" => "Deep Sky Blue",
    "1E90FF" => "Dodger Blue",
    "4169E1" => "Royal Blue",
    "000080" => "Navy",
    "00008B" => "Dark Blue",
    "0000CD" => "Medium Blue",
    "0000FF" => "Blue",
    "8A2BE2" => "Blue Violet",
    "9932CC" => "Dark Orchid",
    "9400D3" => "Dark Violet",
    "800080" => "Purple",
    "8B008B" => "Dark Magenta",
    "FF00FF" => "Fuchsia",
    "FF00FF" => "Magenta",
    "C71585" => "Medium Violet Red",
    "FF1493" => "Deep Pink",
    "FF69B4" => "Hot Pink",
    "DC143C" => "Crimson",
    "A52A2A" => "Brown",
    "CD5C5C" => "Indian Red",
    "BC8F8F" => "Rosy Brown",
    "F08080" => "Light Coral",
    "FFFAFA" => "Snow",
    "FFE4E1" => "Misty Rose",
    "E9967A" => "Dark Salmon",
    "FFA07A" => "Light Salmon",
    "A0522D" => "Sienna",
    "FFF5EE" => "Sea Shell",
    "8B4513" => "Saddle Brown",
    "FFDAB9" => "Peachpuff",
    "CD853F" => "Peru",
    "FAF0E6" => "Linen",
    "FFE4C4" => "Bisque",
    "DEB887" => "Burlywood",
    "D2B48C" => "Tan",
    "FAEBD7" => "Antique White",
    "FFDEAD" => "Navajo White",
    "FFEBCD" => "Blanched Almond",
    "FFEFD5" => "Papaya Whip",
    "FFE4B5" => "Moccasin",
    "F5DEB3" => "Wheat",
    "FDF5E6" => "Oldlace",
    "FFFAF0" => "Floral White",
    "FFF8DC" => "Cornsilk",
    "F0E68C" => "Khaki",
    "FFFACD" => "Lemon Chiffon",
    "EEE8AA" => "Pale Goldenrod",
    "BDB76B" => "Dark Khaki",
    "F5F5DC" => "Beige",
    "FAFAD2" => "Light Goldenrod Yellow",
    "FFFFE0" => "Light Yellow",
    "FFFFF0" => "Ivory",
    "6B8E23" => "Olive Drab",
    "556B2F" => "Dark Olive Green",
    "8FBC8F" => "Dark Sea Green",
    "006400" => "Dark Green",
    "228B22" => "Forest Green",
    "90EE90" => "Light Green",
    "98FB98" => "Pale Green",
    "F0FFF0" => "Honeydew",
    "2E8B57" => "Sea Green",
    "3CB371" => "Medium Sea Green",
    "F5FFFA" => "Mintcream",
    "66CDAA" => "Medium Aquamarine",
    "7FFFD4" => "Aquamarine",
    "2F4F4F" => "Dark Slate Gray",
    "AFEEEE" => "Pale Turquoise",
    "E0FFFF" => "Light Cyan",
    "F0FFFF" => "Azure",
    "5F9EA0" => "Cadet Blue",
    "B0E0E6" => "Powder Blue",
    "ADD8E6" => "Light Blue",
    "87CEEB" => "Sky Blue",
    "87CEFA" => "Lightsky Blue",
    "4682B4" => "Steel Blue",
    "F0F8FF" => "Alice Blue",
    "708090" => "Slate Gray",
    "778899" => "Light Slate Gray",
    "B0C4DE" => "Lightsteel Blue",
    "6495ED" => "Cornflower Blue",
    "E6E6FA" => "Lavender",
    "F8F8FF" => "Ghost White",
    "191970" => "Midnight Blue",
    "6A5ACD" => "Slate Blue",
    "483D8B" => "Dark Slate Blue",
    "7B68EE" => "Medium Slate Blue",
    "9370DB" => "Medium Purple",
    "4B0082" => "Indigo",
    "BA55D3" => "Medium Orchid",
    "DDA0DD" => "Plum",
    "EE82EE" => "Violet",
    "D8BFD8" => "Thistle",
    "DA70D6" => "Orchid",
    "FFF0F5" => "Lavender Blush",
    "DB7093" => "PaleViolet Red",
    "FFC0CB" => "Pink",
    "FFB6C1" => "Light Pink",
    "000000" => "Black",
    "696969" => "Dim Gray",
    "808080" => "Gray",
    "A9A9A9" => "Dark Gray",
    "C0C0C0" => "Silver",
    "D3D3D3" => "Light Grey",
    "DCDCDC" => "Gainsboro",
    "F5F5F5" => "White Smoke",
    "FFFFFF" => "White"
);

$hs['countries'] = array(
    '1' => 'United States',
    '2' => 'Canada',
    '3' => 'Afghanistan',
    '4' => 'Albania',
    '5' => 'Algeria',
    '6' => 'American Samoa',
    '7' => 'Andorra',
    '8' => 'Angola',
    '9' => 'Anguilla',
    '10' => 'Antarctica',
    '11' => 'Antigua and/or Barbuda',
    '12' => 'Argentina',
    '13' => 'Armenia',
    '14' => 'Aruba',
    '15' => 'Australia',
    '16' => 'Austria',
    '17' => 'Azerbaijan',
    '18' => 'Bahamas',
    '19' => 'Bahrain',
    '20' => 'Bangladesh',
    '21' => 'Barbados',
    '22' => 'Belarus',
    '23' => 'Belgium',
    '24' => 'Belize',
    '25' => 'Benin',
    '26' => 'Bermuda',
    '27' => 'Bhutan',
    '28' => 'Bolivia',
    '29' => 'Bosnia and Herzegovina',
    '30' => 'Botswana',
    '31' => 'Bouvet Island',
    '32' => 'Brazil',
    '34' => 'Brunei Darussalam',
    '35' => 'Bulgaria',
    '36' => 'Burkina Faso',
    '37' => 'Burundi',
    '38' => 'Cambodia',
    '39' => 'Cameroon',
    '40' => 'Cape Verde',
    '41' => 'Cayman Islands',
    '42' => 'Central African Republic',
    '43' => 'Chad',
    '44' => 'Chile',
    '45' => 'China',
    '46' => 'Christmas Island',
    '47' => 'Cocos (Keeling) Islands',
    '48' => 'Colombia',
    '49' => 'Comoros',
    '50' => 'Congo',
    '51' => 'Cook Islands',
    '52' => 'Costa Rica',
    '53' => 'Croatia (Hrvatska)',
    '54' => 'Cuba',
    '55' => 'Cyprus',
    '56' => 'Czech Republic',
    '57' => 'Denmark',
    '58' => 'Djibouti',
    '59' => 'Dominica',
    '60' => 'Dominican Republic',
    '61' => 'East Timor',
    '62' => 'Ecuador',
    '63' => 'Egypt',
    '64' => 'El Salvador',
    '65' => 'Equatorial Guinea',
    '66' => 'Eritrea',
    '67' => 'Estonia',
    '68' => 'Ethiopia',
    '69' => 'Falkland Islands (Malvinas)',
    '70' => 'Faroe Islands',
    '71' => 'Fiji',
    '72' => 'Finland',
    '73' => 'France',
    '74' => 'France, Metropolitan',
    '75' => 'French Guiana',
    '76' => 'French Polynesia',
    '77' => 'French Southern Territories',
    '78' => 'Gabon',
    '79' => 'Gambia',
    '80' => 'Georgia',
    '81' => 'Germany',
    '82' => 'Ghana',
    '83' => 'Gibraltar',
    '84' => 'Greece',
    '85' => 'Greenland',
    '86' => 'Grenada',
    '87' => 'Guadeloupe',
    '88' => 'Guam',
    '89' => 'Guatemala',
    '90' => 'Guinea',
    '91' => 'Guinea-Bissau',
    '92' => 'Guyana',
    '93' => 'Haiti',
    '94' => 'Heard and Mc Donald Islands',
    '95' => 'Honduras',
    '96' => 'Hong Kong',
    '97' => 'Hungary',
    '98' => 'Iceland',
    '99' => 'India',
    '100' => 'Indonesia',
    '101' => 'Iran (Islamic Republic of)',
    '102' => 'Iraq',
    '103' => 'Ireland',
    '104' => 'Israel',
    '105' => 'Italy',
    '106' => 'Ivory Coast',
    '107' => 'Jamaica',
    '108' => 'Japan',
    '109' => 'Jordan',
    '110' => 'Kazakhstan',
    '111' => 'Kenya',
    '112' => 'Kiribati',
    '113' => 'Korea, Democratic People\'s Republic of',
    '114' => 'Korea, Republic of',
    '115' => 'Kosovo',
    '116' => 'Kuwait',
    '117' => 'Kyrgyzstan',
    '118' => 'Lao People\'s Democratic Republic',
    '119' => 'Latvia',
    '120' => 'Lebanon',
    '121' => 'Lesotho',
    '122' => 'Liberia',
    '123' => 'Libyan Arab Jamahiriya',
    '124' => 'Liechtenstein',
    '125' => 'Lithuania',
    '126' => 'Luxembourg',
    '127' => 'Macau',
    '128' => 'Macedonia',
    '129' => 'Madagascar',
    '130' => 'Malawi',
    '131' => 'Malaysia',
    '132' => 'Maldives',
    '133' => 'Mali',
    '134' => 'Malta',
    '135' => 'Marshall Islands',
    '136' => 'Martinique',
    '137' => 'Mauritania',
    '138' => 'Mauritius',
    '139' => 'Mayotte',
    '140' => 'Mexico',
    '141' => 'Micronesia, Federated States of',
    '142' => 'Moldova, Republic of',
    '143' => 'Monaco',
    '144' => 'Mongolia',
    '145' => 'Montenegro',
    '146' => 'Montserrat',
    '147' => 'Morocco',
    '148' => 'Mozambique',
    '149' => 'Myanmar',
    '150' => 'Namibia',
    '151' => 'Nauru',
    '152' => 'Nepal',
    '153' => 'Netherlands',
    '154' => 'Netherlands Antilles',
    '155' => 'New Caledonia',
    '156' => 'New Zealand',
    '157' => 'Nicaragua',
    '158' => 'Niger',
    '159' => 'Nigeria',
    '160' => 'Niue',
    '161' => 'Norfork Island',
    '162' => 'Northern Mariana Islands',
    '163' => 'Norway',
    '164' => 'Oman',
    '165' => 'Pakistan',
    '166' => 'Palau',
    '167' => 'Panama',
    '168' => 'Papua New Guinea',
    '169' => 'Paraguay',
    '170' => 'Peru',
    '171' => 'Philippines',
    '172' => 'Pitcairn',
    '173' => 'Poland',
    '174' => 'Portugal',
    '175' => 'Puerto Rico',
    '176' => 'Qatar',
    '177' => 'Reunion',
    '178' => 'Romania',
    '179' => 'Russian Federation',
    '180' => 'Rwanda',
    '181' => 'Saint Kitts and Nevis',
    '182' => 'Saint Lucia',
    '183' => 'Saint Vincent and the Grenadines',
    '184' => 'Samoa',
    '185' => 'San Marino',
    '186' => 'Sao Tome and Principe',
    '187' => 'Saudi Arabia',
    '188' => 'Senegal',
    '189' => 'Serbia',
    '190' => 'Seychelles',
    '191' => 'Sierra Leone',
    '192' => 'Singapore',
    '193' => 'Slovakia',
    '194' => 'Slovenia',
    '195' => 'Solomon Islands',
    '196' => 'Somalia',
    '197' => 'South Africa',
    '198' => 'South Georgia South Sandwich Islands',
    '199' => 'Spain',
    '200' => 'Sri Lanka',
    '201' => 'St. Helena',
    '202' => 'St. Pierre and Miquelon',
    '203' => 'Sudan',
    '204' => 'Suriname',
    '205' => 'Svalbarn and Jan Mayen Islands',
    '206' => 'Swaziland',
    '207' => 'Sweden',
    '208' => 'Switzerland',
    '209' => 'Syrian Arab Republic',
    '210' => 'Taiwan',
    '211' => 'Tajikistan',
    '212' => 'Tanzania, United Republic of',
    '213' => 'Thailand',
    '214' => 'Togo',
    '215' => 'Tokelau',
    '216' => 'Tonga',
    '217' => 'Trinidad and Tobago',
    '218' => 'Tunisia',
    '219' => 'Turkey',
    '220' => 'Turkmenistan',
    '221' => 'Turks and Caicos Islands',
    '222' => 'Tuvalu',
    '223' => 'Uganda',
    '224' => 'Ukraine',
    '225' => 'United Arab Emirates',
    '226' => 'United Kingdom',
    '227' => 'United States minor outlying islands',
    '228' => 'Uruguay',
    '229' => 'Uzbekistan',
    '230' => 'Vanuatu',
    '231' => 'Vatican City State',
    '232' => 'Venezuela',
    '233' => 'Vietnam',
    '238' => 'Yemen',
    '239' => 'Yugoslavia',
    '241' => 'Zambia',
    '242' => 'Zimbabwe'
);

$hs['country_codes'] = array(
    '1' => 'us',
    '2' => 'ca',
    '3' => 'af',
    '4' => 'al',
    '5' => 'dz',
    '6' => 'as',
    '7' => 'ad',
    '8' => 'ao',
    '9' => 'ai',
    '10' => 'aq',
    '11' => 'ag',
    '12' => 'ar',
    '13' => 'am',
    '14' => 'aw',
    '15' => 'au',
    '16' => 'at',
    '17' => 'az',
    '18' => 'bs',
    '19' => 'bh',
    '20' => 'bd',
    '21' => 'bb',
    '22' => 'by',
    '23' => 'be',
    '24' => 'bz',
    '25' => 'bj',
    '26' => 'bm',
    '27' => 'bt',
    '28' => 'bo',
    '29' => 'ba',
    '30' => 'bw',
    '31' => 'bv',
    '32' => 'br',
    '34' => 'bn',
    '35' => 'bg',
    '36' => 'bf',
    '37' => 'bi',
    '38' => 'kh',
    '39' => 'cm',
    '40' => 'cv',
    '41' => 'ky',
    '42' => 'cf',
    '43' => 'td',
    '44' => 'cl',
    '45' => 'cn',
    '46' => 'cx',
    '47' => 'cc',
    '48' => 'co',
    '49' => 'cm',
    '50' => 'cg',
    '51' => 'ck',
    '52' => 'cr',
    '53' => 'hr',
    '54' => 'cu',
    '55' => 'cy',
    '56' => 'cz',
    '57' => 'dk',
    '58' => 'dj',
    '59' => 'dm',
    '60' => 'do',
    '61' => 'tl',
    '62' => 'ec',
    '63' => 'eg',
    '64' => 'sv',
    '65' => 'gq',
    '66' => 'er',
    '67' => 'ee',
    '68' => 'et',
    '69' => 'fk',
    '70' => 'fo',
    '71' => 'fj',
    '72' => 'fi',
    '73' => 'fr',
    '74' => 'fr',
    '75' => 'gf',
    '76' => 'pf',
    '77' => 'tf',
    '78' => 'ga',
    '79' => 'gm',
    '80' => 'ge',
    '81' => 'de',
    '82' => 'gh',
    '83' => 'gi',
    '84' => 'gr',
    '85' => 'gl',
    '86' => 'gd',
    '87' => 'gp',
    '88' => 'gu',
    '89' => 'gt',
    '90' => 'gn',
    '91' => 'gw',
    '92' => 'gy',
    '93' => 'ht',
    '94' => 'hm',
    '95' => 'hn',
    '96' => 'hk',
    '97' => 'hu',
    '98' => 'is',
    '99' => 'in',
    '100' => 'id',
    '101' => 'ir',
    '102' => 'iq',
    '103' => 'ie',
    '104' => 'il',
    '105' => 'it',
    '106' => 'ci',
    '107' => 'jm',
    '108' => 'jp',
    '109' => 'jo',
    '110' => 'kz',
    '111' => 'ke',
    '112' => 'ki',
    '113' => 'kp',
    '114' => 'kr',
    '115' => 'al',
    '116' => 'kw',
    '117' => 'kg',
    '118' => 'la',
    '119' => 'lv',
    '120' => 'lb',
    '121' => 'ls',
    '122' => 'lr',
    '123' => 'ly',
    '124' => 'li',
    '125' => 'lt',
    '126' => 'lu',
    '127' => 'mo',
    '128' => 'mk',
    '129' => 'mg',
    '130' => 'mw',
    '131' => 'my',
    '132' => 'mv',
    '133' => 'ml',
    '134' => 'mt',
    '135' => 'mh',
    '136' => 'mq',
    '137' => 'mr',
    '138' => 'mu',
    '139' => 'yt',
    '140' => 'mx',
    '141' => 'fm',
    '142' => 'md',
    '143' => 'mk',
    '144' => 'mn',
    '145' => 'me',
    '146' => 'ms',
    '147' => 'ma',
    '148' => 'mz',
    '149' => 'mm',
    '150' => 'na',
    '151' => 'nr',
    '152' => 'np',
    '153' => 'nl',
    '154' => 'nl',
    '155' => 'nc',
    '156' => 'nz',
    '157' => 'ni',
    '158' => 'ne',
    '159' => 'ng',
    '160' => 'nu',
    '161' => 'nf',
    '162' => 'mp',
    '163' => 'no',
    '164' => 'om',
    '165' => 'pk',
    '166' => 'pw',
    '167' => 'pa',
    '168' => 'pg',
    '169' => 'py',
    '170' => 'cn',
    '171' => 'ph',
    '172' => 'pn',
    '173' => 'pl',
    '174' => 'pt',
    '175' => 'pr',
    '176' => 'qa',
    '177' => 're',
    '178' => 'ro',
    '179' => 'ru',
    '180' => 'rw',
    '181' => 'kn',
    '182' => 'lc',
    '183' => 'vc',
    '184' => 'ws',
    '185' => 'sm',
    '186' => 'st',
    '187' => 'sa',
    '188' => 'sn',
    '189' => 'rs',
    '190' => 'sc',
    '191' => 'sl',
    '192' => 'sg',
    '193' => 'sk',
    '194' => 'si',
    '195' => 'sb',
    '196' => 'so',
    '197' => 'za',
    '198' => 'gs',
    '199' => 'es',
    '200' => 'lk',
    '201' => 'sh',
    '202' => 'pm',
    '203' => 'sd',
    '204' => 'sr',
    '205' => 'sj',
    '206' => 'sz',
    '207' => 'se',
    '208' => 'ch',
    '209' => 'sy',
    '210' => 'tw',
    '211' => 'tj',
    '212' => 'tz',
    '213' => 'th',
    '214' => 'tg',
    '215' => 'tk',
    '216' => 'to',
    '217' => 'tt',
    '218' => 'tn',
    '219' => 'tr',
    '220' => 'tm',
    '221' => 'tc',
    '222' => 'tv',
    '223' => 'ug',
    '224' => 'ua',
    '225' => 'ae',
    '226' => 'gb',
    '227' => 'um',
    '228' => 'uy',
    '229' => 'uz',
    '230' => 'vu',
    '231' => 'va',
    '232' => 've',
    '233' => 'vn',
    '238' => 'ye',
    '239' => 'rs',
    '240' => 'zm',
    '242' => 'zw'
);
