<div class="modal animated vh-center fadeIn confirm-action-modal" id="confirm-clear-chat">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form id="clear-chat-form">
                <input type="hidden" class="hidden d-none" name="hash" value="<?php echo fetch_or_get($hs['csrf_token'],'none') ?>">
                <div class="modal-header">
                    <h4 class="modal-title">{{TR Please confirm your actions!}}</h4>
                </div>
                <div class="alert alert-danger hidden no-mb">
                    <span class="icon">
                        <?php echo hs_svg('info'); ?>
                    </span>
                    <span class="message"></span>
                </div>
                <div class="alert alert-success hidden no-mb">
                    <span class="icon">
                        <?php echo hs_svg('check-outline'); ?>
                    </span>
                    <span class="message"></span>
                </div>
                <div class="modal-body">
                    <?php echo hs_translate('Are you sure you want to delete all messages in the chat with {%interloc_name%}? Note this action can not be undone!',array('interloc_name' => sprintf("<b>%s</b>",$hs['interloc_data']['name']))); ?>  
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-submit bg-blue">{{TR Yes, delete it!}}</button>
                    <button type="button" class="btn btn-cancel bg-grey" data-dismiss="modal">{{TR No, cancel}}</button>
                </div>
                <input type="hidden" name="item_id" value="">
            </form>
        </div>
    </div>
</div>