<tr class="products" data-prod-list-item="<?php echo($hs['prod_item']['id']); ?>">
    <td>
        <?php echo($hs['prod_item']['id']); ?>
    </td>
    <td class="poster">
        <a href="#" class="poster-holder">
            <img src="<?php echo($hs['prod_item']['thumb']); ?>" alt="Image">
        </a>
    </td>
    <td class="link">
        <a href="#">
            <?php echo($hs['prod_item']['name']); ?>
        </a>
    </td>
    <td>
        <?php if (not_empty($hs['prod_item']['sku'])): ?>
            <b><?php echo($hs['prod_item']['sku']); ?></b>
        <?php else: ?>
            <span>{{TR No}}</span>
        <?php endif; ?>
    </td>
    <td>
        <span class="col-green">  
            <?php echo hs_money($hs['prod_item']['sale_price']); ?>
        </span>
    </td>
    <td>    
        <span class="badge bg-red">{{TR Unsaved}}</span>
    </td>
    <td>
        <span class="col-green"><?php echo hs_money($hs['prod_item']['profit']); ?></span>
    </td>
    <td>
        <div class="dropdown">
            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <i class="material-icons">more_horiz</i>
            </a>
            <ul class="dropdown-menu pull-right bs-dropdown-menu">
                <li>
                    <a href="<?php echo($hs['prod_item']['edit']); ?>" class="waves-effect waves-block">
                        {{TR Edit}}
                    </a>
                </li>
            </ul>
        </div>
    </td>
</tr>