<div class="notifications-page-container">
	<div class="content-container">
		<div class="notifications-list-item no-notifications">
			<div class="icon">
				<?php echo hs_svg('notifications-off'); ?>
			</div>
			<h5>
				{{TR No notifications}}
			</h5>
			<p>
				{{TR Here you will see all the history of your notifications}}
			</p>
			<button data-anchor="{{CONFIG url}}">
				{{TR Go to home page}}
			</button>
		</div>
	</div>
</div>

<footer class="footer-fluid">
	<?php echo hs_loadpage('footer/fluid'); ?>	
</footer>