<script>
    jQuery(document).ready(function($) {
        "use strict";
    	var SITE_SET_PAGE = $('div[data-sblock="site_settings_page"]');
    	var SITE_SET_FORM = SITE_SET_PAGE.find('form[data-snode="site_settings_form"]');

        SITE_SET_PAGE.find('[data-main-btn="submit"]').on('click', function(event) {
            event.preventDefault();
            SITE_SET_FORM.submit();
        });

        SITE_SET_FORM.ajaxForm({
            url: '{{CONFIG url}}/req/admin/save_configs',
            type: 'POST',
            dataType: 'json',
            beforeSend: function() {
                SITE_SET_PAGE.find('[data-main-btn="submit"]').attr('disabled', 'true');
                SITE_SET_PAGE.find('[data-main-btn="submit"]').find('span').text("{{TR Please wait}}!");
                SITE_SET_FORM.find('small.error-message').remove();
            },
            success: function(data) {
                if (data.status == 200) {
                    $.notify({
                        message: data.message,
                    },{
                        allow_dismiss: false,icon_type: "class",type: 'default',timer: 500,
                        placement: {from: "bottom",align: "left"},
                        offset: {x: 40,y: 30},
                        animate: {enter: 'animated fadeInUp',exit: 'animated fadeOutDown'}
                    });

                    SITE_SET_PAGE.find('[data-main-btn="submit"]').removeClass('bg-main-red').addClass("bg-green").find('span').text("{{TR Changes saved}}!");

                    SITE_SET_FORM.find('input[data-snode="site_favicon"]').val('');
                    SITE_SET_FORM.find('input[data-snode="site_logo"]').val('');

                    SITE_SET_FORM.find('div[data-snode="select_site_logo"]').find('span[data-snode="file_name"]').text("{{TR Select logo file}}");
                    SITE_SET_FORM.find('div[data-snode="select_site_favicon"]').find('span[data-snode="file_name"]').text("{{TR Select favicon file}}");  
                } 
                else {
                	SITE_SET_FORM.find('[data-form-field="{0}"]'.format(data.err_field)).scroll2().append($("<small>",{
                		text: data.message,
                		class: 'col-red error-message animated flash'
                	}));
                }
            },
            complete: function() {
            	delay(function() {
                    SITE_SET_PAGE.find('[data-main-btn="submit"]').removeAttr('disabled');
            		SITE_SET_PAGE.find('[data-main-btn="submit"]').removeClass('bg-green').addClass('bg-main-red').find('span').text("{{TR Save changes}}");
            	},3000);
            }
        });

        SITE_SET_FORM.find('div[data-snode="select_site_logo"]').click(function(event) {
            event.preventDefault();
            event.stopPropagation();
            var this_el = $(this);
            SITE_SET_FORM.find('input[name="site_logo"]').trigger('click');
        });

        SITE_SET_FORM.find('input[name="site_logo"]').on('change', function(event) {
            event.preventDefault();
            var file_name  = event.target.files[0].name;
            var name_holdr = SITE_SET_FORM.find('[data-snode="select_site_logo"]').find('[data-snode="file_name"]');

            if (file_name) {
                name_holdr.text(file_name);
            }
            else {
                $.notify({
                    message: 'Error: Could not determine file name!',
                },{
                    allow_dismiss: false,icon_type: "class",type: 'default',timer: 500,
                    placement: {from: "bottom",align: "left"},
                    offset: {x: 40,y: 30},
                    animate: {enter: 'animated fadeInUp',exit: 'animated fadeOutDown'}
                }); name_holdr.text("{{TR Unknown}}");
            }
        });

        SITE_SET_FORM.find('div[data-snode="select_site_favicon"]').click(function(event) {
            event.preventDefault();
            event.stopPropagation();
            var this_el = $(this);
            SITE_SET_FORM.find('input[name="site_favicon"]').trigger('click');
        });

        SITE_SET_FORM.find('input[name="site_favicon"]').on('change', function(event) {
            event.preventDefault();
            var file_name  = event.target.files[0].name;
            var name_holdr = SITE_SET_FORM.find('[data-snode="select_site_favicon"]').find('[data-snode="file_name"]');

            if (file_name) {
                name_holdr.text(file_name);
            }
            else {
                $.notify({
                    message: 'Error: Could not determine file name!',
                },{
                    allow_dismiss: false,icon_type: "class",type: 'default',timer: 500,
                    placement: {from: "bottom",align: "left"},
                    offset: {x: 40,y: 30},
                    animate: {enter: 'animated fadeInUp',exit: 'animated fadeOutDown'}
                }); name_holdr.text("{{TR Unknown}}");
            }
        });

        SITE_SET_PAGE.find('#right-sidepart').stickySidebar({
            topSpacing: 130,
            bottomSpacing: 20,
            stickyClass: 'is-affixed'
        });

        SITE_SET_PAGE.find('[data-affix-scroll]').on('click', function(event) {
            event.preventDefault();
            var this_el = $(this);
            var label   = this_el.data('affix-scroll');
            if (label && SITE_SET_PAGE.find('[data-affix-label="{0}"]'.format(label)).length) {
                SITE_SET_PAGE.find('[data-affix-label="{0}"]'.format(label)).scroll2(200,125);

                this_el.addClass('active');
                this_el.siblings('li.list-group-item').removeClass('active');
            }
        });
    });
</script>