<div class="content-container">
	<div class="empty-page-wrapper">
		<div class="icon">
			<?php echo hs_svg('sad'); ?>
		</div>
		<h5>
			{{TR No products found!}}
		</h5>
		<p>
			{{TR Sorry, there are no products in this category yet}}
		</p>
		<a href="{{back_url}}">
			<button class="btn">
				{{TR Continue shopping}}		
			</button>
		</a>
	</div>
</div>
<footer class="footer-fluid">
	<?php echo hs_loadpage('footer/fluid'); ?>	
</footer>