<div class="withdrawals-page-container" id="withdrawals-page-container">
	<div class="block-header">
	    <nav class="breadcrumbs-cust" aria-label="breadcrumb breadcrumb-cust">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{LINK merchant_panel}}">{{TR Control panel}}</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{{LINK merchant_panel/market_payouts}}">
                        {{TR Market payouts}}
                    </a>
                </li>
                <li class="breadcrumb-item active">
                    {{TR Withdrawals}}
                </li>
            </ol>
        </nav>
	</div>
	<div class="row clearfix">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <div class="info-box info-box-lg bg-blue">
                <div class="box-body">  
                    <div class="content">
                        <div class="flex-cont">      
                            <div class="part-1">
                                <span class="title">
                                    {{TR Total requests}}
                                </span>
                                <span class="text">
                                    <a href="javascript:void(0);">
                                        {{TR Total withdrawal requests}}
                                    </a>
                                </span>
                            </div>
                            <div class="part-2">
                                <span class="num" title="<?php echo($hs['total_reqs']); ?>">
                                    <?php echo($hs['total_reqs']); ?>
                                </span>
                            </div>
                        </div>  
                    </div>
                    <div class="icon">
                        <i class="material-icons">storage</i>
                    </div>
                </div> 
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <div class="info-box info-box-lg bg-green">
                <div class="box-body">  
                    <div class="content">
                        <div class="flex-cont">      
                            <div class="part-1">
                                <span class="title">
                                    {{TR Paid}}
                                </span>
                                <span class="text">
                                    <a href="javascript:void(0);">
                                        {{TR Total paid requests}}
                                    </a>
                                </span>
                            </div>
                            <div class="part-2">
                                <span class="num" title="<?php echo($hs['total_reqs_paid']); ?>">
                                    <?php echo($hs['total_reqs_paid']); ?>
                                </span>
                            </div>
                        </div>  
                    </div>
                    <div class="icon">
                        <i class="material-icons">check_circle</i>
                    </div>
                </div> 
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <div class="info-box info-box-lg bg-orange">
                <div class="box-body"> 
                    <div class="content">
                        <div class="flex-cont">      
                            <div class="part-1">
                                <span class="title">
                                    {{TR Unpaid}}
                                </span>
                                <span class="text">
                                    <a href="javascript:void(0);">
                                        {{TR Total rejected requests}}
                                    </a>
                                </span>
                            </div>
                            <div class="part-2">
                                <span class="num" title="<?php echo($hs['total_reqs_declined']); ?>">
                                    <?php echo($hs['total_reqs_declined']); ?>
                                </span>
                            </div>
                        </div>  
                    </div>
                    <div class="icon">
                        <i class="material-icons">sentiment_very_dissatisfied</i>
                    </div>
                </div> 
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <div class="info-box info-box-lg bg-red">
                <div class="box-body">  
                    <div class="content">
                        <div class="flex-cont">      
                            <div class="part-1">
                                <span class="title">
                                    {{TR Pending}}
                                </span>
                                <span class="text">
                                    <a href="javascript:void(0);">
                                        {{TR Total pending requests}}
                                    </a>
                                </span>
                            </div>
                            <div class="part-2">
                                <span class="num" title="<?php echo($hs['total_reqs_pending']); ?>">
                                    <?php echo($hs['total_reqs_pending']); ?>
                                </span>
                            </div>
                        </div>  
                    </div>
                    <div class="icon">
                        <i class="material-icons">access_time</i>
                    </div>
                </div> 
            </div>
        </div>
    </div>
	<div class="row clearfix">	
	    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	        <div class="card withdrawals-page-card clearfix">
	        	<div class="header">
	                <h2>{{TR Annual market monetization statistics}}</h2>
	            </div>
	            <div class="body">
	                <div class="yearly-stats-chart">
	            		<div class="chart-wrapper">
	            			<canvas id="yearly-stats-display"></canvas>
	            		</div>
	            	</div>
	            </div>
	        </div>
	    </div>
	</div>
	<div class="row clearfix">
	    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
	        <div class="card withdrawals-table-card ajax-ctrl-table">
	            <div class="header un-filterable">
	                <h2>{{TR List of requests from sellers for payout}}</h2>
	            </div>
	            <div class="body table-responsive">
	                <table class="table table-hover no-mb" id="requests-list">
	                    <thead>
	                        <tr class="tt-up">
	                        	<th>ID</th>
	                        	<th>{{TR Requestor}}</th>
	                        	<th>{{TR Balance}}</th>	                        	
	                            <th>{{TR PayPal-Payment Link}}</th>
	                            <th>{{TR Amount}}</th>      
	                            <th>{{TR Status}}</th>
	                            <th>{{TR Date}}</th>
	                            <th>{{TR Action}}</th>
	                        </tr>
	                    </thead>
	                    <tbody>
	                    	<?php if (not_empty($hs['payout_requests'])): ?>
	                    		<?php foreach ($hs['payout_requests'] as $hs['req_data']): ?>
			                        <?php echo hs_loadpage('market_payouts/includes/request_li'); ?>
		                        <?php endforeach; ?>
	                    	<?php else: ?>
	                    		<?php echo hs_loadpage('market_payouts/includes/empty_table'); ?>
	                    	<?php endif; ?> 
	                    </tbody>
	                </table>
	                <?php if (not_empty($hs['payout_requests'])): ?>
		                <div class="data-preloader-wrapper hidden" id="table-preloader">
	                    	<?php echo hs_loadpage('components/data_preloader'); ?>
	                    </div>
		                <a href="javascript:void(0);" class="pagination-ctrls prev">
	                        <i class="material-icons">chevron_left</i>
	                    </a>
		                <a href="javascript:void(0);" class="pagination-ctrls next">
	                        <i class="material-icons">chevron_right</i>
	                    </a>
                    <?php endif; ?> 
	            </div>
	        </div>
	    </div>
	</div>
</div>
<?php echo hs_loadpage('market_payouts/static/js/market_payouts_script'); ?>

<?php if (not_empty($hs['payout_requests'])): ?>
    <?php echo hs_loadpage('market_payouts/modals/confirmations/request_decline'); ?>
    <?php echo hs_loadpage('market_payouts/modals/confirmations/request_payment'); ?>
<?php endif; ?>


