<div class="clearfix" id="documentation-merchant-terms-page">
	<div class="alert alert-info">
        <i class="material-icons">info</i>
        <strong>{{TR Please note}}:</strong> 
        {{TR The content of this page will be publicly available to all visitors to your site and should contain a description of the Seller’s conditions of sale (Terms of sale), which you must agree to and follow before selling any of your products, etc.}}
    </div>
    <div class="block-header">
        <nav class="breadcrumbs-cust" aria-label="breadcrumb breadcrumb-cust">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{LINK merchant_panel}}">{{TR Control panel}}</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{{LINK merchant_panel/doc_merchant_terms}}">
                        {{TR Merchant terms}}
                    </a>
                </li>
                <li class="breadcrumb-item active">
                    {{TR Merchant terms}} ({{CONFIG name}})
                </li>
            </ol>
        </nav>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>{{TR Merchant terms}} ({{CONFIG name}})</h2>
                </div>
                <div class="body">
                	<form class="no-mb" id="form">
                        <input type="hidden" class="hidden d-none" name="hash" value="<?php echo fetch_or_get($hs['csrf_token'],'none') ?>">
                		<div class="form-group">
                			<textarea name="content" rows="15" id="documentation-merchanterms-content"><?php echo($hs['doc_page_content']); ?></textarea>
                		</div>
                		<div class="form-group no-mb">
                			<button type="submit" class="btn bg-blue btn-lg btn-custom">
                                <i class="material-icons">save</i> <span>{{TR Save changes}}</span>         
                            </button>
                		</div>
                	</form>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo hs_loadpage('doc_merchant_terms/static/js/doc_merchant_terms_script'); ?>