<script>
	jQuery(document).ready(function($) {
        "use strict";
        var MARKET_MODERS_LS_PAGE = $("div#market-moders-page");
        var MARKET_MODERS_LIST    = MARKET_MODERS_LS_PAGE.find('table#users-list');
		var MODER_REMOVAL_M       = $("div#confirm-moder-removal-modal");

        MARKET_MODERS_LS_PAGE.find('a.pagination-ctrls').on('click',function(event) {
            event.preventDefault();
            event.stopPropagation();
            if ($(this).hasClass('disabled') != true) { 
                var pager_ctrls = MARKET_MODERS_LS_PAGE.find('a.pagination-ctrls');
                var this_ctrl   = $(this);
                var users_list  = MARKET_MODERS_LS_PAGE.find('table#users-list');
                var pager_dir   = (($(this).hasClass('prev')) ? 'up' : 'down');
                var last_req    = users_list.find('tr[data-user-li]').last().data('user-li');
                var first_req   = users_list.find('tr[data-user-li]').first().data('user-li');
                var preloader   = MARKET_MODERS_LS_PAGE.find('div#table-preloader').removeClass('hidden');
                var pager_ctrls = pager_ctrls.removeClass('disabled');

                $.ajax({
                    url: '{{CONFIG url}}/req/admin/get_market_moders',
                    type: 'GET',
                    dataType: 'json',
                    data: {
                        dir: pager_dir, 
                        last: last_req, 
                        first: first_req
                    },
                }).done(function(data) {
                    if (data.status == 200) {
                        users_list.find('tbody').html(data.html);
                    }
                    else{
                        this_ctrl.addClass('disabled');
                    }
                }).fail(function() {
                    $.notify({
                        message: 'Error: Failed to connect to the server. Please check your internet connection',
                    },{
                        allow_dismiss: false,icon_type: "class",type: 'default',timer: 500,
                        placement: {from: "bottom",align: "left"},
                        offset: {x: 40,y: 30},
                        animate: {enter: 'animated fadeInUp',exit: 'animated fadeOutDown'}
                    });
                }).always(function() {
                    delay(function(){
                        preloader.addClass('hidden');
                    },500);
                });
            }
            else {
                return false;
            }
        });

        $(document).on('click', '[data-onclick]', function(event) {
            event.preventDefault();
            var event_trigger = $(this).data('onclick');
            var zis_el        = $(this);
            if(event_trigger == 'delete_moder') {
                var moder_id = zis_el.data('id');
                MODER_REMOVAL_M.find('input[name="user_id"]').val(moder_id);
                MODER_REMOVAL_M.modal('show');
            }
        });

        MODER_REMOVAL_M.find('form#form').ajaxForm({
            url: '{{CONFIG url}}/req/admin/delete_moder',
            type: 'POST',
            dataType: 'json',
            beforeSend: function() {
                MODER_REMOVAL_M.find('button').attr('disabled', 'true');
            },
            success: function(data) {
                if (data.message) {
                    $.notify({
                        message: data.message,
                    },{
                        allow_dismiss: false,icon_type: "class",type: 'default',timer: 500,
                        placement: {from: "bottom",align: "left"},
                        offset: {x: 40,y: 30},
                        animate: {enter: 'animated fadeInUp',exit: 'animated fadeOutDown'}
                    });
                }

                if (MARKET_MODERS_LIST.find('tr[data-user-li]').length > 1) {
                    if (data.status == 200) {
                        var moder_id = MODER_REMOVAL_M.find('input[name="user_id"]').val();
                        MARKET_MODERS_LIST.find('tr[data-user-li="{0}"]'.format(moder_id)).slideUp(150,function(){
                            $(this).remove();
                        });

                        MODER_REMOVAL_M.find('button').removeAttr('disabled');
                        MODER_REMOVAL_M.find('input[name="user_id"]').val('');
                    }
                }

                else {
                    MARKET_MODERS_LIST.css('opacity', '0.3');
                    $(window).reloadPage(1500);
                } 
            },
            complete: function() {
                MODER_REMOVAL_M.modal('hide');
                MODER_REMOVAL_M.find('button').removeAttr('disabled');
            }
        });
	});
</script>