<div class="content-container">
	<div class="top-line">
		<ul>
			<li>
				<a href="{{LINK privacy_policy}}">
					{{TR Privacy Policy}}
				</a>
			</li>
			<li>
				<a href="{{LINK terms}}">
					{{TR Terms of Use}}
				</a>
			</li>
			<li>
				<a href="{{LINK about}}">
					{{TR About us}}
				</a>
			</li>
			<li>
				<a href="{{LINK contact_us}}">
					{{TR Contact us}}
				</a>
			</li>
			<li>
				<a href="{{LINK merchant_terms}}">
					{{TR Merchant terms}}
				</a>
			</li>
			<li>
				<a href="{{LINK help}}">
					F.A.Q
				</a>
			</li>

			<li class="ml-auto copyright">
				<a href="#">
					&copy; <?php echo date('Y'); ?> {{CONFIG name}} {{TR All rights reserved}}
				</a>
			</li>
		</ul>
	</div>
</div>