<div class="clearfix changelogs-timeline-page" id="changelogs-timeline-page">
    <div class="block-header">
        <nav class="breadcrumbs-cust" aria-label="breadcrumb breadcrumb-cust">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{LINK merchant_panel}}">{{TR Control panel}}</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{{LINK merchant_panel/backup}}">
                        {{TR Changelogs}}
                    </a>
                </li>
                <li class="breadcrumb-item active">
                    {{TR Site changelogs timeline}}
                </li>
            </ol>
        </nav>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2 class="clearfix">
                        v1.0.3 <small class="pull-right"><i class="material-icons">update</i> 01 February, 2020</small>
                    </h2>
                </div>
                <div class="body">
                    <ul>
                        <li>
                            <span class="badge bg-main-red">
                                Bug
                            </span>
                            <span class="changelog-message">
                                <b>[Fixed]</b> Previous several important bugs
                            </span>
                        </li>
                        <li>
                            <span class="badge bg-green">
                                Update
                            </span>
                            <span class="changelog-message">
                                <b>[Improved]</b> User interface design
                            </span>
                        </li>
                        <li>
                            <span class="badge bg-green">
                                Update
                            </span>
                            <span class="changelog-message">
                                <b>[Improved]</b> Removed some restrictions, (required fields, terms, etc..)
                            </span>
                        </li>
                        <li>
                            <span class="badge bg-green">
                                Update
                            </span>
                            <span class="changelog-message">
                                <b>[Added]</b> Multiadmin adding & managing system
                            </span>
                        </li>
                        <li>
                            <span class="badge bg-green">
                                Update
                            </span>
                            <span class="changelog-message">
                                <b>[Added]</b> Payment methods Disabling/Enabling system
                            </span>
                        </li>
                        <li>
                            <span class="badge bg-green">
                                Update
                            </span>
                            <span class="changelog-message">
                                <b>[Added]</b> User blocking system for admin
                            </span>
                        </li>
                        <li>
                            <span class="badge bg-green">
                                Update
                            </span>
                            <span class="changelog-message">
                                <b>[Added]</b> COD payment method. 
                            </span>
                        </li>
                        <li>
                            <span class="badge bg-green">
                                Update
                            </span>
                            <span class="changelog-message">
                                <b>[Added]</b> User/Merchant verification system
                            </span>
                        </li>
                        <li>
                            <span class="badge bg-green">
                                Update
                            </span>
                            <span class="changelog-message">
                                <b>[Added]</b> User editing system for admin
                            </span>
                        </li>
                        <li>
                            <span class="badge bg-green">
                                Update
                            </span>
                            <span class="changelog-message">
                                <b>[Improved]</b> And many more minor changes that improve the quality of the script as a whole
                            </span>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="card">
                <div class="header">
                    <h2 class="clearfix">
                        v1.0.2 <small class="pull-right"><i class="material-icons">update</i> 01 February, 2020</small>
                    </h2>
                </div>
                <div class="body">
                    <ul>
                        <li>
                            <span class="badge bg-main-red">
                                Bug
                            </span>
                            <span class="changelog-message">
                                <b>[Fixed]</b> Several important bugs
                            </span>
                        </li>
                        <li>
                            <span class="badge bg-green">
                                Update
                            </span>
                            <span class="changelog-message">
                                <b>[Improved]</b> Statistics display systems
                            </span>
                        </li>
                        <li>
                            <span class="badge bg-green">
                                Update
                            </span>
                            <span class="changelog-message">
                                <b>[Improved]</b> User interface design
                            </span>
                        </li>
                        <li>
                            <span class="badge bg-green">
                                Update
                            </span>
                            <span class="changelog-message">
                                <b>[Added]</b> Categories management system
                            </span>
                        </li>
                        <li>
                            <span class="badge bg-green">
                                Update
                            </span>
                            <span class="changelog-message">
                                <b>[Added]</b> Languages management system
                            </span>
                        </li>
                        <li>
                            <span class="badge bg-green">
                                Update
                            </span>
                            <span class="changelog-message">
                                <b>[Added]</b> Currencies management system
                            </span>
                        </li>
                        <li>
                            <span class="badge bg-green">
                                Update
                            </span>
                            <span class="changelog-message">
                                <b>[Added]</b> Ability to change the position of a currency symbol
                            </span>
                        </li>
                        <li>
                            <span class="badge bg-green">
                                Update
                            </span>
                            <span class="changelog-message">
                                <b>[Added]</b> Added product enabling and disabling the system for sellers
                            </span>
                        </li>
                        <li>
                            <span class="badge bg-green">
                                Update
                            </span>
                            <span class="changelog-message">
                                <b>[Added]</b> Added product variations editing system
                            </span>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="card">
                <div class="header">
                    <h2 class="clearfix">
                        v1.0.1 <small class="pull-right"><i class="material-icons">update</i> 15 January, 2020</small>
                    </h2>
                </div>
                <div class="body">
                    <ul>
                        <li>
                            <span class="badge bg-main-red">
                                Bug
                            </span>
                            <span class="changelog-message">
                                <b>[Fixed]</b> Several important security issues
                            </span>
                        </li>
                        <li>
                            <span class="badge bg-main-red">
                                Bug
                            </span>
                            <span class="changelog-message">
                                <b>[Fixed]</b> Several layout (interface) bugs
                            </span>
                        </li>
                        <li>
                            <span class="badge bg-green">
                                Update
                            </span>
                            <span class="changelog-message">
                                <b>[Added]</b> Changelogs timeline page
                            </span>
                        </li>
                        <li>
                            <span class="badge bg-green">
                                Update
                            </span>
                            <span class="changelog-message">
                                <b>[Added]</b> Account confirmation system via email
                            </span>
                        </li>
                        <li>
                            <span class="badge bg-green">
                                Update
                            </span>
                            <span class="changelog-message">
                                <b>[Improved]</b> Statistics display systems
                            </span>
                        </li>
                        <li>
                            <span class="badge bg-green">
                                Update
                            </span>
                            <span class="changelog-message">
                                <b>[Added]</b> Several categories
                            </span>
                        </li>
                        <li>
                            <span class="badge bg-green">
                                Update
                            </span>
                            <span class="changelog-message">
                                <b>[Added]</b> Page scrolling button
                            </span>
                        </li>
                        <li>
                            <span class="badge bg-green">
                                Update
                            </span>
                            <span class="changelog-message">
                                <b>[Added]</b> (Logo & Favicon) uploading function to admin panel
                            </span>
                        </li>
                        <li>
                            <span class="badge bg-green">
                                Update
                            </span>
                            <span class="changelog-message">
                                <b>[Added]</b> Advanced settings page
                            </span>
                        </li>
                        <li>
                            <span class="badge bg-green">
                                Update
                            </span>
                            <span class="changelog-message">
                                <b>[Added]</b> Amazon S3 image storage system
                            </span>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="card">
                <div class="header">
                    <h2 class="clearfix">
                        v1.0 <small class="pull-right"><i class="material-icons">update</i> 29 December, 2019</small>
                    </h2>
                </div>
                <div class="body">
                    <ul>
                        <li>
                            <span class="badge bg-blue">
                                Release
                            </span>
                            <span class="changelog-message">
                                Version v1.0 released on 29 December, 2019
                            </span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>