<script>
	jQuery(document).ready(function($) {
		"use strict";
		
		var WITHDR_PAGE_CONT   = $("div#withdrawals-page-container");
		var REQ_DECLINE_M      = $("div#confirm-request-decline-modal");
		var REQ_PAYMENT_M      = $("div#confirm-request-payment-modal");
		var REQUESTS_LIST      = WITHDR_PAGE_CONT.find('table#requests-list');
		var YEARLY_STATS_CHART = document.getElementById('yearly-stats-display').getContext('2d');
		var yearly_stats       = new Chart(YEARLY_STATS_CHART, {
			type: 'bar',
			data: {
				labels: ["{{TR January}}", "{{TR February}}", "{{TR March}}", "{{TR April}}", "{{TR May}}", "{{TR June}}", "{{TR July}}", "{{TR August}}", "{{TR September}}", "{{TR October}}","{{TR November}}","{{TR December}}"],
				datasets: [{
					label: "{{TR Commission income}}",
					borderColor: '#00add8',
					backgroundColor: '#00c0ef',
					fill: false,
					data: <?php echo json($hs['yearly_stats'],1); ?>,
					pointRadius: 5,
					pointHoverRadius: 5,
				}]
			},
			options: {
				responsive: true,
				maintainAspectRatio: false,
				tooltips: { 
                    mode: 'label',
                    intersect: false,
                    callbacks: {
                        label: function(tooltipItem, data) { 
                            let fnum = tooltipItem.yLabel.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
                            let fval = "{0}: {1}";
                            return fval.format(data.datasets[tooltipItem.datasetIndex].label,hs_format_currency(fnum));
                        },
                    }
                },
				hover: {mode: 'nearest',intersect: true
				},
				legend: {position: 'bottom'
				},
				scales: {
					xAxes: [{
						display: true,
						gridLines: {display: true,}
					}],
					yAxes: [{
						display: true,
						gridLines: {display: true,}
					}]
				}
			}
		});

		WITHDR_PAGE_CONT.find('a.pagination-ctrls').on('click',function(event) {
			event.preventDefault();
			event.stopPropagation();
			if ($(this).hasClass('disabled') != true) {	
				var pager_ctrls = WITHDR_PAGE_CONT.find('a.pagination-ctrls');
				var this_ctrl   = $(this);
				var reqs_list   = WITHDR_PAGE_CONT.find('table#requests-list');
				var pager_dir   = (($(this).hasClass('prev')) ? 'up' : 'down');
				var last_req    = reqs_list.find('tr[data-payout-request-li]').last().data('payout-request-li');
				var first_req   = reqs_list.find('tr[data-payout-request-li]').first().data('payout-request-li');
				var preloader   = WITHDR_PAGE_CONT.find('div#table-preloader').removeClass('hidden');

				$.ajax({
					url: '{{CONFIG url}}/req/admin/get_payout_requests',
					type: 'GET',
					dataType: 'json',
					data: {
						dir: pager_dir, 
						last: last_req, 
						first: first_req
					},
				}).done(function(data) {
					if (data.status == 200) {
						reqs_list.find('tbody').html(data.html);
						pager_ctrls.removeClass('disabled');
					}
					else{
						this_ctrl.addClass('disabled');
					}
				}).fail(function() {
					$.notify({
						message: 'Error: Failed to connect to the server. Please check your internet connection',
					},{
					    allow_dismiss: false,icon_type: "class",type: 'default',timer: 500,
					    placement: {from: "bottom",align: "left"},
					    offset: {x: 40,y: 30},
					    animate: {enter: 'animated fadeInUp',exit: 'animated fadeOutDown'}
					});
				}).always(function() {
					delay(function(){
						preloader.addClass('hidden');
					},500);
				});
			}
			else {
				return false;
			}
		});

		$(document).on('click', '[data-onclick]', function(event) {
			event.preventDefault();
			var event_trigger = $(this).data('onclick');
        	var zis_el        = $(this);

        	if (event_trigger == 'decline_po_req') {
        		var req_id = zis_el.data('id');
        		if ($.isNumeric(req_id)) {
        			REQ_DECLINE_M.find('input[name="req_id"]').val(req_id);
        			REQ_DECLINE_M.modal('show');
        		}
        	}

        	else if(event_trigger == 'mark_as_paid') {
        		var req_id = zis_el.data('id');
        		if ($.isNumeric(req_id)) {
        			REQ_PAYMENT_M.find('input[name="req_id"]').val(req_id);
        			REQ_PAYMENT_M.modal('show');
        		}
        	}
		});

		REQ_DECLINE_M.find('form#request-decline-form').ajaxForm({
			url: '{{CONFIG url}}/req/admin/decline_payout_request',
            type: 'POST',
            dataType: 'json',
            beforeSend: function() {
                REQ_DECLINE_M.find('button').attr('disabled', 'true');
            },
            success: function(data) {
                if (data.status == 200) {
                    var req_id = REQ_DECLINE_M.find('input[name="req_id"]').val();
                    REQUESTS_LIST.find('tr[data-payout-request-li="{0}"]'.format(req_id)).slideUp(150,function(){
                        $(this).remove();
                    });
                }

                if (data.message) {
                    $.notify({
                        message: data.message,
                    },{
					    allow_dismiss: false,icon_type: "class",type: 'default',timer: 500,
					    placement: {from: "bottom",align: "left"},
					    offset: {x: 40,y: 30},
					    animate: {enter: 'animated fadeInUp',exit: 'animated fadeOutDown'}
					});
                }

                if (REQUESTS_LIST.find('tr[data-payout-request-li]').length <= 1) {
                    delay(function(){
                    	$(window).reloadPage(300);
                    },1500);
                }

                REQ_DECLINE_M.find('button').removeAttr('disabled');
                REQ_DECLINE_M.find('input[name="req_id"]').val('');
                REQ_DECLINE_M.modal('hide');
            }
		});

		REQ_PAYMENT_M.find('form#request-payment-form').ajaxForm({
			url: '{{CONFIG url}}/req/admin/accept_payout_request',
            type: 'POST',
            dataType: 'json',
            beforeSend: function() {
                REQ_PAYMENT_M.find('button').attr('disabled', 'true');
            },
            success: function(data) {
                if (data.status == 200) {
                    var req_id = REQ_PAYMENT_M.find('input[name="req_id"]').val();
                    REQUESTS_LIST.find('tr[data-payout-request-li="{0}"]'.format(req_id)).slideUp(150,function(){
                        $(this).remove();
                    });
                }

                if (data.message) {
                    $.notify({
                        message: data.message,
                    },{
					    allow_dismiss: false,icon_type: "class",type: 'default',timer: 500,
					    placement: {from: "bottom",align: "left"},
					    offset: {x: 40,y: 30},
					    animate: {enter: 'animated fadeInUp',exit: 'animated fadeOutDown'}
					});
                }

                if (REQUESTS_LIST.find('tr[data-payout-request-li]').length <= 1) {
                    delay(function(){
                    	$(window).reloadPage(300);
                    },1500);
                }

                REQ_PAYMENT_M.find('button').removeAttr('disabled');
                REQ_PAYMENT_M.find('input[name="req_id"]').val('');
                REQ_PAYMENT_M.modal('hide');
            }
		});
	});
</script>