<div class="modal animated vh-center fadeIn popup-ticket-modal" id="account-removal-message-modal" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="ticket-content">
                <div class="ticket-time">
                    <time>
                        <i class="material-icons">report_problem</i> {{TR Reported at}}: <?php echo $hs['report_data']['time']; ?>
                    </time>
                    <div class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <i class="material-icons">keyboard_arrow_down</i>
                        </a>
                        <ul class="dropdown-menu bs-dropdown-menu pull-right">
                            <li>
                                <a href="<?php echo($hs['report_data']['prod_url']); ?>" class="waves-effect waves-block">
                                    {{TR Product page}}
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo($hs['report_data']['seller_url']); ?>" class="waves-effect waves-block">
                                    {{TR Seller profile}}
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="user-info">
                    <div class="avatar">
                        <img src="<?php echo($hs['report_data']['avatar']); ?>" alt="Avatar">
                    </div>
                    <div class="uname">
                        <h6>
                            <a href="#">
                                <?php echo($hs['report_data']['full_name']); ?>

                                <?php if ($hs['report_data']['verified'] == '1'): ?>
                                    <?php echo hs_svg('verified-icon'); ?>
                                <?php endif; ?>
                            </a>
                        </h6>
                        <p>
                            <span>
                                <?php echo($hs['report_data']['email']); ?>
                            </span>
                        </p>
                    </div>
                </div>
                <div class="ticket-message">
                    <div class="ticket-message-header">
                        <h5>
                            {{TR Report Message}}:
                        </h5>
                    </div>
                    <p class="message2reviwer">
                        <?php echo($hs['report_data']['report']); ?>
                    </p>
                </div>
                <div class="ticket-ctrls">
                    <button type="button" data-dismiss="modal" class="btn bg-main-red btn-block btn-sm waves-effect">
                        {{TR Close report message}}
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>