<div class="clearfix" id="site-languages-page">
    <div class="block-header">
        <nav class="breadcrumbs-cust" aria-label="breadcrumb breadcrumb-cust">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{LINK merchant_panel}}">{{TR Control panel}}</a>
                </li>
                <li class="breadcrumb-item">
                    {{TR Localization}}
                </li>
                <li class="breadcrumb-item active">
                    {{TR Languages}}
                </li>
            </ol>
        </nav>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>{{TR Manage market languages}}</h2>
                </div>
                <div class="body table-responsive">
                    <table class="table common-table table-striped" id="languages-list">
                        <thead>
                            <tr>
                                <th>{{TR Sort order}}</th>
                                <th>
                                    {{TR Language name}}
                                </th>
                                <th>
                                    {{TR Status}}
                                </th>
                                <th>
                                    {{TR Country banner}}
                                </th> 
                                <th>
                                    {{TR Alpha-2 Code}}
                                </th>
                                <th>
                                    {{TR Usage}}
                                </th>
                                <th>
                                    {{TR Action}}
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($hs['all_langs'] as $hs['lang_data']): ?>
                                <?php echo hs_loadpage('site_languages/includes/language_li'); ?>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<button title="{{TR Add new language}}" type="button" class="fixed-right-bottom btn bg-main-red btn-circle waves-effect waves-circle waves-float" data-toggle="modal" data-target="#addnew-language-modal">
    <i class="material-icons">add</i>
</button>
<?php echo hs_loadpage('site_languages/static/js/site_languages_script'); ?>
<?php echo hs_loadpage('site_languages/modals/change_lang_sortorder'); ?>
<?php echo hs_loadpage('site_languages/modals/add_new_language'); ?>
<?php echo hs_loadpage('site_languages/modals/delete_language'); ?>