<div class="modal animated vh-center fadeIn confirm-action-modal" id="confirm-bitem-purge-removal-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">{{TR Please confirm your actions!}}</h4>
            </div>
            <div class="modal-body">
                {{TR Are you sure you want to remove all selected items from the basket? If not, click Cancel to save your basket for later or add these items to your wishlist!}}
            </div>
            <div class="modal-footer">
                <button type="button" id="remove-selected-items" class="btn btn-submit bg-blue">{{TR Yes, delete it!}}</button>
                <button type="button" class="btn btn-cancel bg-grey" data-dismiss="modal">{{TR No, cancel}}</button>
            </div>
        </div>
    </div>
</div>